### ISSUE TITLE
Formalise rules for required properties.

### ISSUE THREAD

**Issue by wwqrd** [codaco/protocol-validation#11]
Required properties are made up of a mixture of those that are required by NC/Server and
those that have been arbitrarily defined as required.

This has two drawbacks:
- It is possible to create a protocol that is legible to all applications, but not "valid"
- There are multiple sources of truth for what fields are required in a protocol.

# New guidelines for interface properties

- Fields should only be consided required if they needed properties in Network Canvas (and to a smaller extent, Server).
- Omitted values are implicitly `falsy`.
- For nested properties, if a field not being required would make it's parent node empty, then this field is *also* not required.
  
  For example:
  ```js
  // If this protocol was valid:
  {
    stages: [
      {
        type: 'Narrative'
        behaviour: {
          freeDraw: false, // And this field was not required by NC
        },
      }
    ],
    ...
  }

  // This protocol would also be valid (and would mean the same thing)
  {
    stages: [
      {
        type: 'Narrative',
      }
    ],
    ...
  }
  ```

# Future interface design

Example interface configuration for Name Generator:

```js
{
  // Required by all interfaces:
  "label": "Sage", // used for navigation in network canvas
  "type": "NameGenerator", // a unique name for this type of interface

  // Optional property to define manipulated entity:
  "subject": {
    "entity": "node",
    "type": "a3a0f38b-9f18-4abc-9e81-b580dbaf0395"
  },

  // Interface specific properties:
  "form": {
    "title": "Form title",
    "fields": [
      {
        "variable": "eeb35fca-36ff-4e62-8042-8d299209cfa5",
        "prompt": "Mwfmiwf"
      }
    ]
  },
  "prompts": [
    {
      "id": "43d3fe0e-17bf-4508-89af-aeba88fb0309",
      "text": "A prompt"
    }
  ]
},
```

### Interface specific property guidelines

- Only be required when Network Canvas functionality depends on property to function, for example, a `layoutVariable` in a `Sociogram` interface.
- Avoid deep nesting where possible, ideally no more than 3 deep. This helps to keep the protocol readable.
- Use arrays for iterable items, this helps to make the protocol easy to parse in Network Canvas and easy to edit in Architect.

# Revise existing interfaces to match new guidelines

We will need to revise existing interfaces to ensure they follow the new guidelines.

## Checklist for implementation
- For each interface:
  - [ ] Check usage in Network Canvas to determine whether or not proprety is required
  - [ ] Update Network Canvas to handle unspecified properties where they are not required.
  - [ ] Update Network Canvas documentation for interface
  - [ ] Update protocol-validation to match changes
  - [ ] Update Architect forms to ensure required fields match those in Network Canvas,

**Comment by jthrilly** [comment]
Closing as no longer valid.
