### ISSUE TITLE
Protocol patching feature

### ISSUE THREAD

**Issue by wwqrd** [codaco/protocol-validation#24]
There should be a facility to patch protocols in response to bugs.

- Versions should be able to have multiple patches applied for a specific schema version, e.g. one for each bug.
- Patches should be defined like reducers/migrations, e.g. `(protocol) => protocol`
- We will only run patches that match the schema version, this won't need to patch between versions the way migrations does.
- Suggested implementation: Can we use validation errors as an input to drive patches, e.g.
  `(protocol, errors) => errors.forEach(...)`

**Comment by jthrilly** [comment]
Use-case we had in mind when discussing this:

Version A of Architect contains a bug that creates invalid protocols. Version B of Architect is released to fix this bug. Schema versions are unaltered between these releases. 

When opening a protocol that has been saved in a malformed state by version A, version B will attempt (and fail) to validate the protocol, but will offer to optionally run any available 'patches' against this protocol to try to fix the error.

Knowing that the error existed, we created a patch function in Version B that specifically rectifies the consequences of this bug.

When the user agrees to run the patch, a new version of the protocol file is created with the output.
