### ISSUE TITLE
Enforcement of other required attributes

### ISSUE THREAD

**Issue by wwqrd** [codaco/protocol-validation#35]
JM: This is a meta issue to remind us to revisit the enforcement of required attributes and properties in the protocol schema. We suspect we aren't enforcing everything.

## Meta issues
- [ ] Investigate if validation is even working correctly

## Validation to add
- [ ] variable parameters that depend on input component aren't conditionally validated (e.g DatePicker and RelativeDatePicker)

**Comment by jthrilly** [comment]
Closing as no longer valid.
