### ISSUE TITLE
Build a migration for variable names and option values

### ISSUE THREAD

**Issue by wwqrd** [codaco/protocol-validation#38]
For interoperability variable names, and categorical/ordinal option values must be constrained.

There needs to be a migration to update older protocols.

- properties to respect the constraint:
  `/^[a-zA-Z0-9._\\-:]*$/`
- update all node/edge/ego **variable names**, e.g.
  `codebook.node[uid].variables[variableUid].name`
- update all categorical/ordinal **options values**, e.g.
  `codebook.node[uid].variables[variableUid].options[].value`
- Should also include making stage name unique: https://github.com/codaco/Architect/issues/650

**Comment by jthrilly** [comment]
Migration should also include rich information for the user, including the ability to link to a documentation article.

**Comment by jthrilly** [comment]
Migration should also include rich information for the user, including the ability to link to a documentation article.

**Comment by jthrilly** [comment]
Migration should also include making stage name unique: https://github.com/codaco/Architect/issues/650
